language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8

install:
    - python -m pip install cython

script:
    - python setup.py check
    - python setup.py build_ext --inplace --force
    - python setup.py test
